[project]
name = "youtube-script"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "google-auth-oauthlib>=1.2.3",
    "google-genai>=1.55.0",
    "protobuf>=6.33.2",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
]
